<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV4zcDB3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV4zcDB3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV4zcDB3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV4zcDB3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV4zcDB3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V4zcDB3',
    'container.build_id' => 'c5f52334',
    'container.build_time' => 1629283010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV4zcDB3');
